#!/bin/bash
#===============================================================================
#
#          FILE:  guessgame.sh
# 
#         USAGE:  ./guessgame.sh 
# 
#   DESCRIPTION:  This is a number guessing game. The user has 5 chances
#                 to guess a random number between 1 and 10.
# 
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:   (), 
#       COMPANY:  
#       VERSION:  1.0
#       CREATED:  03/06/2017 10:37:37 PM PST
#      REVISION:  ---
#===============================================================================

#Add game over after 5 unsuccessful attempts
#Add wrong speed option

#Game introduction set to the variable setTitle

setTitle() {
echo -e Hello, this game checks your knowledge of the multiplication table.
}
setTitle -e

read -p  "Please choose your speed in seconds. Options: 4, 7, 10: 
" selected_speed

setStopwatch(){
sleep $selected_speed && xterm -fg yellow -g 240x80 &
}

let attempts=9
let counter=0
let wrong_attempts=0

echo "Let's start!"

while [ $counter -le  $attempts ]
do
#generation of two random numbers, A and B
A=$((RANDOM%11))
B=$((RANDOM%11))
Z=A*B
echo $A x $B = 
read input

  if [[ input -eq Z ]]
  then 
  echo "That is correct!"
  counter=$((counter+1))
   
  elif [[ input -ne Z ]] 
  then
             while [[ input -ne Z ]]
             do
             wrong_attempts=$((wrong_attempts+1))
                 if [[ wrong_attempts -gt 4 ]]
                    then
                    echo "Too many incorrect answers. 
                    Learn the damn multiplication table!"
                    exit 0                    
                 else
                 echo -e "Wrong answer. Try harder!"
                 echo $A x $B = 
                 read input
                 fi
             done
             wrong_attempts=0
             echo That is correct!
  fi 
counter=$((counter+1))
done
echo "Next level!"
