#!/bin/bash
#===============================================================================
# 
#   DESCRIPTION:  This is a calculator game. 
# 
#  REQUIREMENTS:  Good memory
#          BUGS:  System message "Terminated" at the very end of the program
#         NOTES:  
#        AUTHOR:  Olga Makarova 
#       COMPANY:  
#       VERSION:  1.0
#       CREATED:  11/01/2018 10:37:37 PM PST
#      REVISION:  1.0
#===============================================================================


#Function setTitle introduces the game.
setTitle() {
echo -e Hello, this game checks your knowledge of the multiplication table.
}


#Here we call the setTitle function
setTitle -e

#Function setSpeed introduces the speed of the game at user's choice.
#There is a case statement inside the setSpeed function,  it adds funny comments depending on the user's choice. 
setSpeed(){
echo -e Please choose your speed in seconds. Options: 20, 30, 40: `echo $'\n  '` 
 
read speed

case $speed in
    20)
    echo -e Bolsy '\n'
    ;;
    30)
    echo -e OK '\n'
    ;;
    40)
    echo -e Tartaruga!'\n'
    ;;
    *)
    echo -e Pay attention! '\n'
    ;;
    esac
}

#Here we call the setSpeed function
setSpeed


#Conditional until-loop. If the user's speed is not equal to the game conditions (20, 30 or 40) the function setSpeed will keep popping up, requesting the user to set the speed.  
until [[ $speed -eq 20 ]] || [[ $speed -eq 30 ]] || [[ $speed -eq 40 ]]
do 
setSpeed
done


#variable "s" is set to the time left to play the game. Initially we set it to 1 in order to meet the condition of s > 0
s=1

#This is the setStopwatch function. There is a while-loop inside of this function. The function calculates the time left for the game:
#Time left = the speed input by the user - (current time - the time when we started the game).
#The loop keeps counting time down. The system goes to sleep for a second, 
#then wakes up and performs the equation, and keeps doing it until s equals 0. 
#When s is equal to 0 the trap command traps the completion of the loop and sends
# the signal to stop the game. 
setStopwatch(){
while [[ s -gt 0 ]]
do
s="$((speed - (SECONDS - start)))"
echo -e "seconds left: $s"
sleep 0 
done
trap "kill 0  " EXIT
exit 0
}

let attempts=10
let counter=0
let wrong_attempts=0

echo "Let's start!"
start="$SECONDS"

#This is the main while-loop (WHILE_LOOP_1). The game keeps on while the counter is less than 10 attempts
#With every attempt the counter increases by 1 
while [[ $counter -le  $attempts ]] 
do

#generation of two random numbers, A and B
A=$((RANDOM%11))
B=$((RANDOM%11))
Z=A*B

#the program asks the user to multiply random number A by random number B
echo -e "$A x $B = "

#the program reads user's input
read input

#Here we call the setStopwatch program to start the timer. 
#The results of setStopwatch program are transferred to a time_output.txt file
# created automatically when the user starts the game
setStopwatch > time_output.txt 2>&1 &

#If-statement. If user's input equals Z, which means it is correct, the program echos "That is correct!",#echos the time left, goes to the very end of the script, increases the counter by 1 
#and starts a new problem 
  if [[ input -eq Z ]]
  then 
  echo -e "\rThat is correct!"

#New variable "output" is introduced. "Output" is the last line of the time_output.txt file.
#Time left for the game is written in the time_output.txt.file
  output=`tail -n 1 time_output.txt| cat`

#After every successful attempt the program echos time left, it gets it from the time_output.txt file
  echo -e "$output"
  counter=$((counter+1))

#Otherwise, if the user's answer is incorrect...
  elif [[ input -ne Z ]] 
  then


#... then the program starts a while-loop, WHILE_LOOP_2
# while the answer does not equal "Z", which is the correct answer, the program counts wrong attempts.
             while [[ input -ne Z ]]
             do
             wrong_attempts=$((wrong_attempts+1))
# If there are more than 4  wrong attempts the game is over.
                 if [[ wrong_attempts -gt 4 ]]
                    then
                    echo "Too many incorrect answers." 
                    echo "Learn the damn multiplication table!"
#The program exits if the previous command executed successfully
                    exit 0                    

#Else, if the number of attempts is less than 4, then the program prompts the user to try harder!
                 else
                 echo -e "Wrong answer. Try harder!"
                 output=`tail -n 1 time_output.txt| cat`
                 echo -e "$output"
                 echo $A x $B = 
                 read input
                 fi
#End of WHILE_LOOP_2. The user gave a correct answer equalling "Z".
             done

#The program zeros the number of wrong attempts until the next multiplication statement
             wrong_attempts=0
             echo That is correct. Thank you!
             output=`tail -n 1 time_output.txt| cat`
             echo -e "$output"
  fi 
#The counter increases by 1 after every attempt in the main loop (WHILE_LOOP_1).
counter=$((counter+1))

#End of WHILE_LOOP_1. The user gave correct answers within the limit of attempts and time. 
done
echo "Next level!"

