#!/bin/bash
#===============================================================================
#
#          FILE:  guessgame.sh
# 
#         USAGE:  ./guessgame.sh 
# 
#   DESCRIPTION:  This is a number guessing game. The user has 5 chances
#                 to guess a random number between 1 and 10.
# 
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:   (), 
#       COMPANY:  
#       VERSION:  1.0
#       CREATED:  03/06/2017 10:37:37 PM PST
#      REVISION:  ---
#===============================================================================


#Game introduction set to the variable setTitle

setTitle() {
echo -e Hello, this game checks your knowledge of the multiplication table.
}
setTitle -e

read -p  "Please choose your speed in seconds. Options: 4, 7, 10: 
" selected_speed

let attempts=9
let counter=0
while [ $counter -le  $attempts ]
do
#generation of two random numbers, A and B
A=$((RANDOM%11))
B=$((RANDOM%11))
Z=A*B
echo $A x $B = 
read input
counter=$((counter+1))
  if [[ input -eq Z ]]
  then 
  echo "That is correct!"
  else 
  echo -e "\nWrong answer. Try harder!"
  fi
    done
echo "Next level!"
